eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11221/eureka, http://localhost:11222/eureka
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.seyfe.CustomerService.domain
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
